setx = ("green", "blue")
sety = ("blue", "yellow")
print("Original set elements:")
print(setx)
print(sety)
print("\nIntersection of Set X and Set Y:")
setz = set(setx).intersection(set(sety))
print(setz)
print("\nUnion of Set X and Set Y:")
setz = set(setx).union(set(sety))
print(setz)
print("\nDifference of Set X and Set Y:")
setz = set(setx).difference(set(sety))
print(setz)
print("\nSymmetric Difference of Set X and Set Y:")
setz = set(setx).symmetric_difference(set(sety))
print(setz)